### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by slomp**
Hi there,

Here are a few changes I made to the plugin in order to support more recent stable releases of RenderDoc (v0.26).
In addition, I also fixed a crash that happens when the running a cook server instance of UE4.
I have also removed a compilation warning with regard to the plugin calling a deprecated UE4.8 constructor.

I hope you find this useful.

### CODE REVIEW

**Comment by baldurk** [comment]
Nice!

Btw, I think [this capture the plugin does on startup](https://github.com/Temaran/UE4RenderDocPlugin/blob/master/RenderDocPlugin/Source/RenderDocPlugin/Private/RenderDocPluginModule.cpp#L166) is no longer needed, as the pull request the TODO comment mentions got merged a while ago. Someone with UE4 though should probably test that.

**Comment by slomp** [comment]
Hello again, and thanks for the prompt reply!

I will definitely check this startup hack next week and report back (since I am not at work at the moment).

I should have also mentioned that the changes I made also work with the most recent nightly builds of renderdoc.

Cheers!

**Comment by baldurk** [comment]
No problem. FYI I'm not Temaran so I can't comment directly on the pull request, but it looks good to me :). Yes I added the new API for release 0.26 and the minor version bump since then will still work on the recent nightly builds, since it's backwards compatible. I'm probably going to make a new stable release soon, but the API I'm supporting now should be forwards and backwards compatible so it should continue to work indefinitely.

**Comment by slomp** [comment]
Oh, did not even look at your username last time; the legendary creator o RenderDoc!
I am glad to make your acquaintance.

Many thanks for the feedback.
Since you are here, I hope you don't mind addressing one point of confusion that I have.
Previously, the plugin was [issuing these calls](https://github.com/slomp/UE4RenderDocPlugin/blob/master/RenderDocPlugin/Source/RenderDocPlugin/Private/RenderDocPluginModule.cpp#L101) which I commented out.
I am not sure which new API calls are supposed to supersede them.

Cheers

**Comment by baldurk** [comment]
I think those calls are only for [getting SocketPort to pass to renderdocui.exe on launch](https://github.com/slomp/UE4RenderDocPlugin/blob/master/RenderDocPlugin/Source/RenderDocPlugin/Private/RenderDocPluginGUI.cpp#L52) so they're now irrelevant. That whole section of code is _probably_ redundant now, as there are API calls to [see if the UI is connected, and if not launch it](https://github.com/slomp/UE4RenderDocPlugin/blob/91fed57217e9501e17e87ebb1060d30259d2c936/RenderDocPlugin/Source/RenderDocPlugin/Private/renderdoc_app.h#L366-L378). For the Unity integration, on capture I just did something like:

``` cpp
if(!RenderDoc->IsRemoteAccessConnected())
{
   RenderDoc->LaunchReplayUI(true, "");
}
```

Which checks if the UI is already connected and does nothing if it is (the user will have a list of captures in the connection window), and if there is no UI it launches a new one. You can tweak the behaviour if you want - at the moment this plugin I think will always fetch the path to the last capture and launch a new renderdoc window to immediately open it.

**Comment by slomp** [comment]
Understood.
I will make sure to run some tests on this next Tuesday.
This will possibly result in another pull request.
Thanks again for the feedback.

**Comment by slomp** [comment]
All right, pull request updated.
I run some tests just to make sure and found a few issues.
I also added a mechanism to automatically toggle UE4 Draw Events (GPU Markers) when a capture is requested.

**Comment by baldurk** [comment]
FYI in the call to LaunchReplayUI, the first parameter is a 'connect to remote access', which replaces the SocketPort and --remoteaccess stuff in the parameters, that's what I was meaning. So if you set that to true you can remove the `--remoteaccess localhost:%u` string in the parameters and it just becomes the log filename.

**Comment by slomp** [comment]
Many thanks for the feedback.
Is there a way (argument) to automatically open the newest capture file when the LaunchReplayUI() is invoked?

**Comment by baldurk** [comment]
Not at the moment but it's something I could easily add. E.g. if %LATEST_CAPTURE% appears in the argument string, then it's replaced with the full path to the last capture. That would only work on newer RenderDoc versions though, rather than 0.26, so if you want to keep that behaviour of opening the latest log when the UI starts then best to keep that part of the code.

**Comment by slomp** [comment]
Well, I am actually neutral on this matter.
Not sure about Temaran's stance on this, though.
I will wait until these changes are merged into his master branch and then we follow from that.
Meanwhile I will keep these changes in a local branch for future verification.

**Comment by Temaran** [comment]
Hello!

Sorry I could not get to this faster, I've been out of the country through work a lot lately, so my git-hub diligence has been slipping!

This is awesome, thank you for the pull request, I'm merging it now :)

**Comment by slomp** [comment]
Hi Temaran,

Thank you for merging my changes.
I have also made a few [changes (cleanup) on one of my own branches](https://github.com/slomp/UE4RenderDocPlugin/tree/cleanup) based on some feedback/recommendations from baldurk.
These changes make use of the recent renderdoc API to launch the replay UI.
However, the captured snapshot will no longer be opened automatically.
It will instead be added to the snapshot list inside the renderdoc UI and the user must double click it to open/explore the snapshot.

I am neutral as to which behavior is more appropriated, but decided to keep as it is for the moment and hear your opinion first before issuing a pull request.
If you think that moving to the new API way of doing things is more beneficial, feel free to give it a go on my [cleanup branch](https://github.com/slomp/UE4RenderDocPlugin/tree/cleanup).
I can make a formal pull request later if you wish, or you can go ahead and merge/publish it yourself.

Thanks again!

**Comment by Temaran** [comment]
I think that's a good idea since I think most users workflow is doing several captures anyway for comparison. I would love if you made a pull request for it :)

**Pull request merged**
