### PR TITLE
New feature: whole frame capture

### PR DESCRIPTION
**Pull request by slomp**
Hi there,

I added new setting for capturing the entire rendering activity of an engine update tick.
This way, it is possible to intercept the rendering commands of SceneCaptures, of the Editor UI, of Material/Cascade Editor previews, content browser asset thumbnail previews, etc.

In order to do so, I had to refactor the plugin as an "Input Device" plugin, since the regular plugin module interface is unable to listen and respond to engine ticks.

I have also increased the version number and updated the documentation.

That's all, cheers!

### CODE REVIEW

**Comment by Temaran** [comment]
Oh wow :dancer: 

I'll go through the changeset when I get home today :)
Glorious!

**Comment by slomp** [comment]
Hello again,

I am working on a plugin "unification" so that we no longer need to rely on two plugins. To that end, I am afraid the codebase will have to undergo a somewhat aggressive amount of  refactoring/refurbishing/restructuring.

It is still on the early stages, but it is functional. If you are interested in checking the progress, feel free to browse the `unification` branch on my fork. The error reporting/logging has also improved a bit, with less confusing error messages and less redundancy. 

If you agree with the unification, perhaps it would be better to put the current pull-request in hold for now until I finish the unification.

Cheers!

**Comment by Temaran** [comment]
Oh, that's very interesting!

So you mean integrating the renderdoc loader with the main plugin? I'll
have to have a look at that!

/Temaran

2016-05-22 2:16 GMT+02:00 Marcos Paulo Berteli Slomp <
notifications@github.com>:

**Comment by slomp** [comment]
Yes, that's correct. The unified plugin has to be a PreInit/PostConfigInit plugin -- just like the Loader was -- in order to hook the RenderDoc DLL before any rendering context is created.

The main difference is that I am now registering a delegate/callback for when the Level Editor gets loaded (the Level Editor is a plugin by itself, usually loaded at "Default" time). Once the Level Editor has been loaded, the "non-loader" portion of the RenderDoc plugin logic can run and initialize toolbar extensions, commands, etc.

Other than that, the only other difference is that the plugin has been changed to an Input Device plugin, for the reasons I explained in the introduction post of this pull request.

**Comment by Temaran** [comment]
oo

2016-05-23 16:09 GMT+02:00 Marcos Paulo Berteli Slomp <
notifications@github.com>:

**Comment by slomp** [comment]
Hello again,

I gave the final touches, solved the remaining bugs of the unified plugin, and tested it on different environments and in a production environment. Documentation has been updated as well.
All seems to be going well, and I am confident enough to push the changes to the master branch.

Unfortunately, I was not able to work on a proper refactoring of the many module components/source files, so I just made sure everything is in place and did as few changes as possible to the existing code base. Perhaps in another occasion when I am less busy I can resume this refactoring.

Feel free to review the changes before making them official.
If you have any questions, just drop me a message :-)

**Comment by Temaran** [comment]
Excellent!

I've been a bit busy at work during the last week, but I'm planning to go
through this and the previous changeset during the weekend!
Amazing stuff!

/Temaran

2016-05-25 14:43 GMT+02:00 Marcos Paulo Berteli Slomp <
notifications@github.com>:

**Comment by slomp** [comment]
No sweat, take your time :-)

I will be super busy this weekend as I am moving to a new residence, so I am afraid I will only be able to answer your questions (fairly sporadically) next week.

In any case, when you bring the changes to the master branch, I think it would be nice to mark the commit with a `UE4.10` and `UE4.11` tags. If you happen to test it with an earlier version of the engine, please create other tags accordingly as well.

PS: I will be adding some items to the TODO list as well by the end of the day.
There are a few things I would like to sort out for the future, for example, making callstack capture work.

**Pull request merged**
