### PR TITLE
More changes to better suit UE4.15

### PR DESCRIPTION
**Pull request by slomp**
Hi there,

A few extra fixes for non-unity builds, as well as an #include overhaul in order to adhere to the new IWYU (include-what-you-use) paradigm introduced by UE4.15.

The documentation has also been updated, as well as the RenderDoc API header (from RenderDoc v0.33).

Thanks!

### CODE REVIEW

**Comment by Temaran** [comment]
Cool bananas! I'll look it through as soon as I can.

**Comment by Temaran** [comment]
I tried, it but it won't build on the 4.15 binary build I was using
The IWYU paradigm seems to work quite inconsistently on the projects I've been on so far. I'll wait a bit more before tackling it :)

**Comment by Temaran** [comment]
Just out of curiosity, are you on 4.15 source or binary? Also, are you adding the plugin as an engine plugin if you're on source? I get IWYU warnings on my engine level code in one of the source build projects I'm working on

**Comment by slomp** [comment]
I am on UE4.15 source (tested both on a heavily modified licensee codebase, as well as in a pristine UE4 github worktree). Do you also get build errors if you just build the UE4 in isolation?

**Comment by Temaran** [comment]
I only tested as a project plugin in a binary 4.15 build. I do a lot of
research work in 4.15 and 4.16 source atm though, and it seems to work
there.

Hmm. Well I think the best option is still to wait though.

/Temaran

2017-03-28 3:26 GMT+02:00 Marcos Paulo Berteli Slomp <
notifications@github.com>:

**Comment by slomp** [comment]
Yes, it's better to make sure we have it working as a project plugin as well.
I think I can do some testing on the weekend.

For a project plugin on top of a binary build, where should I obtain the UE4 binaries from?

Thanks!

**Pull request merged**
